NEWS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("newspaper.urls")),
    path('summernote/', include('django_summernote.urls')),
    path("api/v1/",include("api.urls")),
]


from django.conf import settings 
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

api/urls.py
from django.urls import include, path
from rest_framework import routers

from api import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'tags', views.TagViewSet)
router.register(r'categories', views.CategoryViewSet)
router.register(r'posts', views.PostViewSet , basename="post-api")



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

newspaper/models.py
from django.db import models

class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(TimeStampModel):
    name= models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Tag(TimeStampModel):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Post(TimeStampModel):
    STATUS_CHOICES = [
        ("active","Active"),
        ("inactive","Inactive"),
    ]

    title = models.CharField(max_length=200)
    content= models.TextField()
    featured_image = models.ImageField(upload_to ="post_images/%y/%m/%d", blank=False)
    author= models.ForeignKey("auth.User",on_delete=models.CASCADE)
    status=models.CharField(max_length=20,choices=STATUS_CHOICES,default="active")
    views_count=models.PositiveBigIntegerField(default=0)
    published_at=models.DateTimeField(null=True,blank=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    tag=models.ManyToManyField(Tag)


    def __str__(self):
        return self.title
    

class Contact(TimeStampModel):
    message = models.TextField()
    name = models.CharField(max_length=100)
    email= models.EmailField()
    subject= models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class UserProfile(TimeStampModel):
    user = models.OneToOneField("auth.User",on_delete=models.CASCADE)
    image= models.ImageField(upload_to="User_image/%Y/%m/%d",blank=False)
    address= models.CharField(max_length=200)
    biography = models.TextField()

    def __str__(self):
        return self.user.username
    
class Comment(TimeStampModel):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    comment= models.TextField()
    name = models.CharField(max_length=50)
    email= models.EmailField()

    def __str__(self):
        return f"{self.email} | {self.comment[:70]}"
    
class Newsletter(TimeStampModel):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email

templates/aznews/list/right/category.html
  
                        <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Category</h4>
                            <ul class="list cat-list">
                                {% for category in categories %}
                                <li>
                                    <a href="{% url 'post-by-category' category.pk %}" class="d-flex">
                                        <p>{{ category.name|title }}</p>
                                        <p>({{ category.post_set.count }})</p>
                                    </a>
                                </li>
                            


                                {% endfor %}
                                
                            </ul>
                        </aside>

templates/aznews/list/right/newsletter.html
<aside class="single_sidebar_widget newsletter_widget">
    <h4 class="widget_title">Newsletter</h4>
    <div id="newsletter_side_message"></div>

    <form action="" method="post" id="newsletter_side_form">
        {% csrf_token %}
        <div class="form-group">
            <input type="email" class="form-control" onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter email'" placeholder='Enter email' 
                name="email"
                required>
        </div>
        <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
            type="submit">Subscribe</button>
    </form>
</aside>

templates/aznews/list/right/popular_posts.html
<aside class="single_sidebar_widget popular_post_widget">
    <h3 class="widget_title">Recent Post</h3>

        {% for trending_post in trending_posts  %}
            <div class="media post_item">
                <img src="{{ trending_post.featured_image.url }}" alt="{{ trending_post.title }}"
                    width="150 px"
                    height="80px" />
                <div class="media-body">
                    <a href="{% url 'post-detail' trending_post.pk %}">
                        <h3>{{ trending_post.title|truncatechars:30 }}</h3>
                    </a>
                    <p>{{ trending_post.published_at|date:"F j, Y" }}</p>
                </div>
            </div>
        {% endfor %}
   
</aside>

templates/aznews/list/right/search_form.html
<aside class="single_sidebar_widget search_widget">
    <form action="{% url 'post-search' %}" method="get">
        <div class="form-group">
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder='Search Keyword'
                    onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Search Keyword'"
                    name="query" />
                <div class="input-group-append">
                    <button class="btns" type="button"><i class="ti-search"></i></button>
                </div>
            </div>
        </div>
        <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
            type="submit">Search</button>
    </form>
</aside>

templates/aznews/list/right/tags.html
<aside class="single_sidebar_widget tag_cloud_widget">
    <h4 class="widget_title">Tag Clouds</h4>
    <ul class="list">
        {% for tag in tags %}
            <li>
                <a href="{% url 'post-by-tag' tag.pk %}">{{ tag.name }}</a>
            </li>        
        {% endfor %}              
    </ul>
</aside>